### ISSUE TITLE
Getting "Process didn't exit successfully: `target/debug/rusted` (signal: 11)" when using into_raw_mode()

### ISSUE THREAD

**Issue by paezao** [Ticki/libterm#6] opened 2016-03-09 10:29 UTC
Hello Ticki,

Im trying to use libterm on macosx to play around with terminal UI stuff and Im getting that error on this line:
let mut stdout = stdout().into_raw_mode().unwrap();

You got any clue on what could be going on? Im using Mac Osx and also Im new to Rust so I'm sorry if that's a stupid error on my part.

Thanks!

**Comment by paezao** [comment] 2016-03-09 10:50
I debugged with gdb and got this:

Program received signal SIGSEGV, Segmentation fault.
0x00000001000048be in rusted::raw::W.IntoRawMode::into_raw_mode (self=<error reading variable: Cannot access memory at address 0x95f8>)
    at /Users/user/.cargo/git/checkouts/libterm-cfb8814c8a0f5aca/master/src/raw.rs:67
67	        let (mut ios, err) = get_terminal_attr();

**Comment by Ticki** [comment] 2016-03-09 10:58
Great catch. Unfortunately, I don't have a Mac OS X computer, so I need you to give me a stack trace. Signal 11 is SIGSERV (segfault), which is definitely not intended. Also, can you give me your Rust version number and head commit?

Thanks
/ticki

**Comment by Ticki** [comment] 2016-03-09 10:59
Oh, you already answered my request ;P

**Comment by paezao** [comment] 2016-03-09 11:01
rustc 1.7.0 (a5d1e7a59 2016-02-29)

**Comment by Ticki** [comment] 2016-03-09 11:01
What happens if you switch to nightly?

**Comment by paezao** [comment] 2016-03-09 11:02
I wish I knew how to do that lol. I'll look into it.

**Comment by Ticki** [comment] 2016-03-09 11:02
Check out the Rust book, it got instructions. There is also `multirust`, which manages Rust versions.

**Comment by paezao** [comment] 2016-03-09 11:06
Okay, I changed to nightly and got the exact same error on gdb.

**Comment by Ticki** [comment] 2016-03-09 11:07
You're running the `simple` example, right?

**Comment by Ticki** [comment] 2016-03-09 11:07
And you're on the latest master?

**Comment by paezao** [comment] 2016-03-09 11:08
Yes and yes

**Comment by paezao** [comment] 2016-03-09 11:47
Let me know if you need any more info

**Comment by Ticki** [comment] 2016-03-09 11:50
Unfortunately, I am not able to reproduce it, so it is near to impossible for me to fix it.

**Comment by paezao** [comment] 2016-03-09 11:52
Do you have a gitter chat or something we can chat in real time about this? I can try and find a way to fix it.

**Comment by Ticki** [comment] 2016-03-09 11:55
I'll have to go for a lecture in half an hour, so I can't do it right now, but if you're on IRC, we can chat, when I get home again.

**Comment by paezao** [comment] 2016-03-09 11:56
I am in IRC yes. What channel are you in?

**Comment by Ticki** [comment] 2016-03-09 11:58
I don't have time right now, but in a few hours, I'll get on mozilla IRC (username is ticki).

**Comment by paezao** [comment] 2016-03-09 11:59
Cool, I'm there all the time, nickname is nkr

**Comment by Ticki** [comment] 2016-03-09 12:08
Ok, thanks.

**Comment by Ticki** [comment] 2016-03-09 16:30
I'm on the chat now.

**Comment by Ticki** [comment] 2016-03-10 11:49
This is fixed now.

**Closed by Ticki** 2016-03-10 11:49 UTC
Labels: bug, help wanted, needs repro
